# Generated by Django 6.1 on 2026-08-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
