# Generated by Django 6.1 on 2026-09-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
            ],
        ),
    ]
