# Generated by Django 6.1 on 2026-09-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0004_post1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='audio',
            field=models.FileField(null=True, upload_to='madia/music'),
        ),
    ]
