# Generated by Django 6.1 on 2026-09-07 08:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0006_post_audio_alter_planet_dob_alter_planet_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='music/'),
        ),
    ]
