# Generated by Django 6.1 on 2026-09-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0008_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
