# Generated by Django 6.1 on 2026-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0009_supportmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
